# Generated by Django 5.1.7 on 2025-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(unique=True, verbose_name='学号'),
        ),
    ]
